telegram-rs/telegram-bot

src/types/mod.rs, src/types/test.rs
Will now decode `GroupChat`s correctly too. Thanks @neuschaefer for the report #4 and test.
=> Fix Chat::decode

src/types/mod.rs
Another fix: It was not correct before but strangely it worked for single objects. Now it should be correct. Fixes #8
=> Fix Chat::decode (worked before sometimes... magically)

src/lib.rs
Apparently I haven't really understood the Rust closure types yet. But long_pull should accept a FnMut to give the user more freedom.
=> Hotfix: Change `long_poll` to take `FnMut`

Cargo.toml, src/lib.rs
Hotfix: `long_poll` takes `FnMut` to give the user more freedom.
=> Version 0.1.2

Cargo.toml, examples/features.rs, examples/simple.rs, src/error.rs, src/lib.rs
A new version with some breaking changes.
- `Bot` was renamed to `Api`
- `long_poll` was replaced by the `Listener` type
- `new` was replaced by `from_token` and `from_env`
- Replaced the `UserInterupt` error by `ListeningAction`
Also: Cleanup and documentation improvements.
=> Version 0.2.0

Cargo.toml, README.md, examples/features.rs, examples/simple.rs, src/error.rs, src/lib.rs, src/types/mod.rs
This is a summary with all the changes (I think that I didn't missed any change :smile:  )
- `try_field` macro: Instead of creating a closure and passing it to Decodable::decode, apply that function directly
- `Response`: Added `error_code: Option<Integer>`, this is a parameter that you get if something went wrong
- `Audio`: Added performer and title, both `Option<String>`, this was added the 15 August in the API
- `Voice`: Added Voice type, this was added the 15 August in the API
- `Message`: The 30 july they made some changes in the Api, this is one of them, adding an optional `caption` field to the Message structure. The 15 August they added the optional `voice` field.
- `MessageType` enum: Changed `Photo(PhotoSize)` for `Photo(Vec<PhotoSize>)` because you receive a list of images, …
=> Added multipart support, send files methods and some updates and changes in the API, details in the description :)

src/types/mod.rs
This is just to make it work, the field is actually named `reply_to_message`, not `reply`, it'd propably be more useful to change the field's name in the API, too.
Added a fix for `forward`, which didn't get the right values from the API as well, while splitting forward in the original two components. The main reason for this is that it was a quick fix to make my bot work, but with the current state of documentation, I think it's useful to just keep to the original names from the telegram API.
=> Fix handling of replies to a message

Cargo.toml, README.md, examples/features.rs, examples/simple.rs, src/lib.rs, src/types/mod.rs, src/types/test.rs
Merges:
- #21 — update Type for Contact;
- #24 — fix handling of replies to a message, but joins `forward_from` and `forward_date` into a single field `forward`.
Fixes:
- #19 — update API, mostly, without File and getFile and and inline bots support.;
- #23 — add supergroup support;
- #25 — add parse_mode to sendMessage method;
- #27 — update chat type;
- fix some compiler warnings.
=> Api update

Cargo.toml, src/lib.rs
Hyper 0.8 was released and I had trouble building the 0.4.1 version of telegram-bot.
I beleave the reason is the multipart package, which was changed by hyper.
=> Update hyper to version 0.8

src/types/mod.rs, src/types/test.rs
Messages with unknown types leads to bot hanging, so we can treat such messages as unknown and process it in regular way.
Related with: #43
=> Handle messages with unknown type

raw/src/types/message.rs
Due to Telegram Bot API specifications:
The PhotoSize property should be an array and cause an error that could be not handled until the update will parsed correctly.
=> Fix property on NewChatPhoto struct (issue #92)

raw/src/types/message.rs
The "media_group_id" was missing in the Message struct, is very useful to identify albums
=> Integrated new "media_group_id" field for Message struct

raw/src/types/message.rs
Not sure if fields' privacy was intended. If so, please propose a different solution.
=> Expose MessageEntity's fields

raw/src/types/chat_member.rs
ChatMember struct was missing of some useful fields for specific admin permissions.
=> Added missing fields for ChatMember

raw/src/types/message.rs
Add's the set_name optional string to the Sticker struct.
=> Add set_name to Sticker struct

lib/src/connector.rs
After [API change](https://github.com/hyperium/hyper-tls/commit/86f4c00c13c182bf7306b388051b7440684bef71#diff-31bbf71c54bca98a0ae3d40a327af940R37) in latest `hyper-tls` telegram-bot don't compile.
Fixed
=> Fix HttpsConnector

lib/Cargo.toml
The current master didn't build. I've bumped the versions of the hyper and futures-preview crates and pinned the hyper-tls crate to the current git commit (They updated their hyper version which caused the current master to stop building).  
All tests ran successfully.
=> Updated hyper and futures-preview, pinned hyper-tls rev

lib/src/util/messages.rs
Apparently I forgot to return message thumbnails as files as well. These are indeed 'files' attached to the message to they should be returned.
=> Add thumbnails to message file list as well

raw/src/types/inline_query_result.rs
Resolves #121 .
I left the builder for `InlineQueryResultArticle` in to maintain backwards compatibility, but didn't add builders for the rest of `InlineQueryResult` types.
=> Add missing InlineQueryResult types

.github/workflows/fmt.yml, .github/workflows/test.yml, README.md
I think we can try actions without disabling travis builds for now.
It tests project with toolchain from `rust-toolchain` file, beta and nightly. It also checks formatting with rustfmt.
=> Set up GitHub Actions

.github/workflows/test.yml, lib/Cargo.toml, lib/examples/features.rs, lib/examples/live_location.rs, lib/src/api.rs, lib/src/connector/hyper.rs, raw/Cargo.toml, raw/src/types/text.rs, rust-toolchain
Hyper 0.13 (and Hyper-tls 0.4) stable was released 8 days ago, following tokio 0.2
I upgraded all alpha dependencies to stable.
* `tokio::timer` is now `tokio::time`
* `Timeout::new` no longer exists and has been replaced by the `timeout` function
* `timer::delay` now longer exists and has been replaced by `timer::delay_for`
* `hyper::client::Client` requires `Clone`, `Send`, and `Sync` for the Connector
* `hyper_tls::HttpsConnector::new` doesn't return a `Result` anymore
* `bytes::Bytes` v0.5 no longer implements `Extend<u8>`, the fix to aggregate the body is to use `hyper::body::to_bytes`
* `bytes::Bytes` doesn't copy the `&str` anymore in `From` implementation and requires an owned string instead
I also incremented the version of telegram-bot and telegram-bot-raw to `0.7.0`, and …
=> Upgrade all dependencies to stable tokio 0.2

raw/src/requests/send_message.rs
This PR fixes an error that occurs after sending a reply to a `ChannelPost`.
Replying to a `ChannelPost` results in the following error:
```
Error: Error(Raw(Error(Json(Error("Missing `from` field for Message", line: 1, column: 356)))))
```
```rust
async fn handle_message<M>(api: &Api, message: M) -> Result<(), Error>
where
M: MessageText + WithTimestamp + CanReplySendMessage,
{
match message.text() {
Some(ref text) => match text.as_str() {
"/my_command" => {
// This line returns the following error after replying to a `ChannelPost`:
// "Missing `from` field for Message".
let response = api.send(message.text_reply(command_response)).await?;
Ok(())
}
_ => Ok(()),
},
None => Ok(()),
}
}
#[tokio::main]
async fn main() -> Result<(), Error> {
dotenv().ok();
let token = …
```
=> Account for when a `ChannelPost` is returned from `SendMessage`

lib/src/stream.rs
As per https://github.com/telegram-rs/telegram-bot/issues/192, `UpdatesStream` does not implement `Send` because the trait object is not inferred to implement `Send`. This PR fixes it, allowing streams to be used with `tokio::spawn` and such.
=> Make UpdatesStream Send
